import type { Metadata } from 'next';
import './globals.css';
import NavbarContainer from '@/components/layout/navbar';
import { outfit } from '@/common/libs/font/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <NavbarContainer />
        {children}
      </body>
    </html>
  );
}
